GET http://localhost:8080/users/1
Accept: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "fullName": "Jimmy Caxton",
  "email": "jimmy@caxton.com"
}

###
GET http://localhost:8080/users
Accept: application/json

###
